version: "3.5"
services:
  dev:
    container_name: init-stack-dev
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ".:/init-stack"
      - "./.aws:/root/.aws"
      - "./zshrc:/root/.zshrc"
      - init-stack-cache:/cache
      - /var/run/docker.sock:/var/run/docker.sock

      # (find src* | grep  '/bin$' && find src* | grep  '/obj$' && find tests* | grep  '/bin$' && find tests* | grep  '/obj$')  | sed 's/^/ - \/init-stack\//'
      - /init-stack/src/InitStack.Cmd/bin
      - /init-stack/src/InitStack.Cmd/obj
      - /init-stack/tests/InitStack.Cmd.Tests/bin
      - /init-stack/tests/InitStack.Cmd.Tests/obj
    environment:
      - ASPNETCORE_ENVIRONMENT=development
      - HISTFILE=/cache/.bash_history
    entrypoint: top -b
    logging:
      driver: none

volumes:
  init-stack-cache:
